### ISSUE TITLE
controller is in a CrashLoopBackOff loop

### ISSUE THREAD

**Issue by tuxtof** [Jont828/cluster-api-addon-helm#11]
controller is in a CrashLoopBackOff loop

quick cluster status

- delete in progress but stalled for other reason
- helmchartproxies are already deleted 
- helmreleaseproxies are present

caaph is crashing with folloing logs

```
I0712 11:27:59.680460       1 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr=":8080"
I0712 11:27:59.680951       1 webhook.go:124] "controller-runtime/builder: Registering a mutating webhook" GVK="addons.cluster.x-k8s.io/v1alpha1, Kind=HelmChartProxy" path="/mutate-addons-clus
ter-x-k8s-io-v1alpha1-helmchartproxy"
I0712 11:27:59.681025       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/mutate-addons-cluster-x-k8s-io-v1alpha1-helmchartproxy"
I0712 11:27:59.681058       1 webhook.go:153] "controller-runtime/builder: Registering a validating webhook" GVK="addons.cluster.x-k8s.io/v1alpha1, Kind=HelmChartProxy" path="/validate-addons-
cluster-x-k8s-io-v1alpha1-helmchartproxy"
I0712 11:27:59.681072       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/validate-addons-cluster-x-k8s-io-v1alpha1-helmchartproxy"
I0712 11:27:59.681112       1 webhook.go:124] "controller-runtime/builder: Registering a mutating webhook" GVK="addons.cluster.x-k8s.io/v1alpha1, Kind=HelmReleaseProxy" path="/mutate-addons-cl
uster-x-k8s-io-v1alpha1-helmreleaseproxy"
I0712 11:27:59.681136       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/mutate-addons-cluster-x-k8s-io-v1alpha1-helmreleaseproxy"
I0712 11:27:59.681160       1 webhook.go:153] "controller-runtime/builder: Registering a validating webhook" GVK="addons.cluster.x-k8s.io/v1alpha1, Kind=HelmReleaseProxy" path="/validate-addon
s-cluster-x-k8s-io-v1alpha1-helmreleaseproxy"
I0712 11:27:59.681171       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/validate-addons-cluster-x-k8s-io-v1alpha1-helmreleaseproxy"
I0712 11:27:59.681214       1 main.go:146] "setup: starting manager"
I0712 11:27:59.681245       1 server.go:217] "controller-runtime/webhook/webhooks: Starting webhook server"
I0712 11:27:59.681334       1 internal.go:369] "Starting server" kind="health probe" addr=":8081"
I0712 11:27:59.681357       1 certwatcher.go:131] "controller-runtime/certwatcher: Updated current TLS certificate"
I0712 11:27:59.681385       1 internal.go:369] "Starting server" path="/metrics" kind="metrics" addr=":8080"
I0712 11:27:59.681391       1 server.go:271] "controller-runtime/webhook: Serving webhook server" host="" port=9443
I0712 11:27:59.681443       1 certwatcher.go:85] "controller-runtime/certwatcher: Starting certificate watcher"
I0712 11:27:59.681526       1 leaderelection.go:248] attempting to acquire leader lease caaph-system/5a2dee3e.cluster.x-k8s.io...
I0712 11:28:17.724738       1 leaderelection.go:258] successfully acquired lease caaph-system/5a2dee3e.cluster.x-k8s.io
I0712 11:28:17.726970       1 controller.go:186] "Starting EventSource" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy" source="kind sourc
e: *v1alpha1.HelmChartProxy"
I0712 11:28:17.727014       1 controller.go:186] "Starting EventSource" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy" source="kind sourc
e: *v1beta1.Cluster"
I0712 11:28:17.727026       1 controller.go:186] "Starting EventSource" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy" source="kind sourc
e: *v1alpha1.HelmReleaseProxy"
I0712 11:28:17.727034       1 controller.go:194] "Starting Controller" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy"
I0712 11:28:17.727910       1 controller.go:186] "Starting EventSource" controller="helmreleaseproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy" source="kind s
ource: *v1alpha1.HelmReleaseProxy"
I0712 11:28:17.727924       1 controller.go:194] "Starting Controller" controller="helmreleaseproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy"
I0712 11:28:17.829453       1 controller.go:228] "Starting workers" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy" worker count=10
I0712 11:28:17.829945       1 controller.go:228] "Starting workers" controller="helmreleaseproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy" worker count=10
E0712 11:28:17.841741       1 controller.go:329] "Reconciler error" err="failed to get kubeconfig for cluster: context \"default-context\" does not exist" controller="helmreleaseproxy" control
lerGroup="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy" HelmReleaseProxy="default/cilium-cluster2-kcwlr" namespace="default" name="cilium-cluster2-kcwlr" reconcileID=15c3b9ee-b172
-4c8a-9c62-3f5847e11a3c
I0712 11:28:17.980828       1 controller.go:118] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="helmreleaseproxy" controllerGrou
p="addons.cluster.x-k8s.io" controllerKind="HelmReleaseProxy" HelmReleaseProxy="default/nutanix-cloud-provider-cluster2-22vgw" namespace="default" name="nutanix-cloud-provider-cluster2-22vgw"
reconcileID=8cf25e35-bc74-4378-bf3b-8e9653b2cc3b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x192720c]

goroutine 190 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:119 +0x1b0
panic({0x1be6800, 0x36e5800})
    runtime/panic.go:884 +0x20c
sigs.k8s.io/cluster-api-addon-provider-helm/internal.generateHelmUninstallConfig(...)
    sigs.k8s.io/cluster-api-addon-provider-helm/internal/helm_operations.go:461
sigs.k8s.io/cluster-api-addon-provider-helm/internal.UninstallHelmRelease({0x23381c8?, 0x4000344630?}, {0x40010cd000?, _}, {{{0x400087c050, 0x7}, {0x400087c060, 0x7}, {0x400087c058, 0x8}, ...}
, ...})
    sigs.k8s.io/cluster-api-addon-provider-helm/internal/helm_operations.go:482 +0x5c
sigs.k8s.io/cluster-api-addon-provider-helm/controllers/helmreleaseproxy.(*HelmReleaseProxyReconciler).reconcileDelete(0x2360b30?, {0x23381c8, 0x4000344630}, 0x4000bac000, {0x40010cd000, 0x15a
f})
    sigs.k8s.io/cluster-api-addon-provider-helm/controllers/helmreleaseproxy/helmreleaseproxy_controller.go:259 +0x594
sigs.k8s.io/cluster-api-addon-provider-helm/controllers/helmreleaseproxy.(*HelmReleaseProxyReconciler).Reconcile(0x400086e810, {0x23381c8, 0x4000344630}, {{{0x400087c030, 0x7}, {0x400077e1e0,
0x25}}})
    sigs.k8s.io/cluster-api-addon-provider-helm/controllers/helmreleaseproxy/helmreleaseproxy_controller.go:141 +0x7d8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x23381c8?, {0x23381c8?, 0x4000344630?}, {{{0x400087c030?, 0x1ad1260?}, {0x400077e1e0?, 0x4000980e18?}}})
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40003d6960, {0x2338120, 0x4000529000}, {0x1cb5d00?, 0x400004cac0?})
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323 +0x2e4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40003d6960, {0x2338120, 0x4000529000})
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274 +0x1b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:231 +0x294
```

**Comment by Jont828** [comment]
I believe this should be fixed by #94. What's curious is that we're getting this reconciler error `failed to get kubeconfig for cluster: context \"default-context\" does not exist` and yet it's still progressing to the nil pointer error you're seeing. Could you try it out on main to see if you're having the same issue?
